apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
    type: front-end
spec:
  containers:
  - name: nginx-pod
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
