apiVersion: v1
kind: Service
metadata:
  name: tooling
  labels:
    name: service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: tooling-app